config/routes.rb
Rails.application.routes.draw do
  resources :anagrams

  root 'anagrams#index'

end

app/models/anagram.rb
require "i18n"

class Anagram < ActiveRecord::Base

  validates_presence_of :sentence, :sentence2

  def check_anagram(anagrams)
    sentence = I18n.transliterate(anagrams[:sentence]).downcase
    sentence2 = I18n.transliterate(anagrams[:sentence2]).downcase

    i = 0
    if sentence.size == sentence2.size
      return anagram(sentence, sentence2, i) ? true : false
    end

    false
  end

  def anagram(sentence, sentence2, i)

    current_sentence = sentence.gsub(/\s+/, "").split('')

    current_sentence.each { |s|
      unless sentence2.include? s
        return false
      end
    }

    i == 1 ? true : anagram(sentence2, sentence, i+=1)

  end

end

app/controllers/anagrams_controller.rb
class AnagramsController < ApplicationController
  before_action :set_anagram, only: [:show, :edit, :update, :destroy]

  def index
    @anagram = Anagram.new
  end

  def create
    @anagram = Anagram.new(anagram_params)
    is_anagram = @anagram.check_anagram(anagram_params)

    respond_to do |format|
      if @anagram.save && is_anagram
        @anagram.is_anagram = true
        format.html { redirect_to :back, notice: 'Its an anagram' }
      else
        @anagram.is_anagram = false
        format.html { redirect_to :back, notice: 'Its not an anagram' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_anagram
      @anagram = Anagram.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def anagram_params
      params.require(:anagram).permit(:sentence, :sentence2, :is_anagram)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/anagrams_helper.rb
module AnagramsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/anagrams/_form.html.erb
<%= form_for(@anagram) do |f| %>
  <% if @anagram.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@anagram.errors.count, "error") %> prohibited this anagram from being saved:</h2>

      <ul>
      <% @anagram.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% end %>

app/views/anagrams/edit.html.erb
<h1>Editing Anagram</h1>

<%= render 'form' %>

<%= link_to 'Show', @anagram %> |
<%= link_to 'Back', anagrams_path %>

app/views/anagrams/index.html.erb
<%= form_for @anagram do |f| %>
    <div class="panel panel-default">
      <div class="panel-heading"><strong> Check Anagram </strong>  </div>
      <div class="panel-body">
        <div class="row">
          <div class="col-lg-12">
            <div class="form-group">
              <b> Word/Sentence 1:</b>
              <%= f.text_field :sentence, class: "form-control" %>
            </div>

            <b> Word/Sentence 2:</b>
            <div class="form-group" align="center">
              <%= f.text_field :sentence2, class: "form-control" %>
            </div>

            <div align="center">
              <%= button_tag(:class => "btn btn-primary btn-lg") do %>
                  Check <span class="glyphicon glyphicon-ok"></span>
              <% end %>
            </div>

          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/anagrams/new.html.erb
<h1>New Anagram</h1>

<%= render 'form' %>

<%= link_to 'Back', anagrams_path %>

app/views/anagrams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sentence:</strong>
  <%= @anagram.sentence %>
</p>

<p>
  <strong>Is anagram:</strong>
  <%= @anagram.is_anagram %>
</p>

<%= link_to 'Edit', edit_anagram_path(@anagram) %> |
<%= link_to 'Back', anagrams_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DesafioRD</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

    <header class="navbar navbar-default" role="navigation">
      <div class="navbar-inner">
        <div class="container">
          <div id="logo" class="navbar-brand"><%= link_to "Desafio RD", root_path %></div>

        </div>
      </div>
    </header>

    <div id="main_content" class="container">
      <% flash.each do |name, msg| %>
          <%= content_tag(:div, msg, class: "alert alert-info") %>
      <% end %>

      <div id="content" class="col-md-9 center-block">
        <!-- Yield identifies a section where content from the view should be inserted. -->
        <%= yield %>
      </div>
    </div>
</body>
</html>